### ISSUE TITLE
网页登陆QQ的缓存路径

### ISSUE THREAD

**Issue by JiZhi-Error** [KyuubiRan/QQCleaner#1]
/storage/emulated/0/tencent/msflogs/com/tencent/mobileqq
网页登陆QQ的缓存

**Comment by ketal178** [comment]
msflogs
一看就不是网页的啊
是MSF进程拉的屎

**Comment by KyuubiRan** [comment]
> msflogs
> 一看就不是网页的啊
> 是MSF进程拉的屎

你改改
