### ISSUE TITLE
微信无法打开

### ISSUE THREAD

**Issue by changyexing** [KyuubiRan/QQCleaner#10]
LSP 1.2.2
微信
![image](https://user-images.githubusercontent.com/47708150/110625639-a1a91b00-81da-11eb-9310-e2a059bf5dc8.png)
LSP勾选微信，重启后，打开微信黑屏，卡死

**Comment by KyuubiRan** [comment]
打开微信就卡死吗？试试最新版 实在不行换个版本 按理来说我的模块不会造成打开微信就卡死的状况

**Comment by changyexing** [comment]
那算了😊宁可不能用也不升级。多谢老哥

**Comment by KyuubiRan** [comment]
你模块版本是多少 试试最新的1.4.4看看有没有入口

**Comment by changyexing** [comment]
还是进不去应用🤣我没关系，用不了也没什么影响
