### ISSUE TITLE
关于支持更多疼逊的垃圾文件目录的建议

### ISSUE THREAD

**Issue by phoenixxie7** [KyuubiRan/QQCleaner#11]
尊敬是开发者，最近在使用这个模块之后，发现很好用。然后某天看到了[清浊逆向工程初始创建](https://github.com/linwinfil/qingzhuo/tree/master/data%E6%95%B0%E6%8D%AE/tasks)这个项目，里面几乎详细的包含了一些常用app的产生的垃圾的目录，请问有计划支持更多嘛？

**Comment by KyuubiRan** [comment]
如果是微信/TIM/QQ的话 增加目录是可以的 如果是其他APP的话暂时不打算做支持 其他应用反响大的话未来可能会加入适配吧

**Comment by phoenixxie7** [comment]
好的。了解了
