### ISSUE TITLE
存在未清理目录

### ISSUE THREAD

**Issue by Gokou-Ruri** [KyuubiRan/QQCleaner#12]
Google play版微信7.0.21
该目录下存在N多个数百K到1M的log文件，看样子是小程序的日志文件。
/storage/emulated/0/Android/data/com.tencent.mm/MicroMsg/wxanewfiles
ps：不知道能不能将这些log目录改为“只读”(chmod 400）？定期清理不如干脆不让它们写入，还能减少磁盘i/o，增加闪存寿命呢（雾）。

**Comment by KyuubiRan** [comment]
你试试用强力模式看看能不能删
（只读模式的话 用MT应该能改 试试看呗
