### ISSUE TITLE
打不开清理界面

### ISSUE THREAD

**Issue by Gokou-Ruri** [KyuubiRan/QQCleaner#13]
Google play版QQ，点击“瘦身”按钮没有任何反应。
同样play版的微信7.0.21可以打开。
框架：lsp 1.2.2
模块：1.5.1
系统：Android 11
![Screenshot_20210318-093403_QQ](https://user-images.githubusercontent.com/26711804/111560361-488a4a00-87cd-11eb-9bb5-55780a087c69.png)

**Comment by KyuubiRan** [comment]
没有特别做过谷歌版的适配呢 能不能用比较随缘 有些人可以用有些人有不行

**Comment by sakuyamaij** [comment]
希望能够加入支持

**Comment by KyuubiRan** [comment]
我这边play版没问题可以正常使用 没法复现 暂时无解咯
