### ISSUE TITLE
1.3.0之后的版本打不开设置

### ISSUE THREAD

**Issue by Womsxd** [KyuubiRan/QQCleaner#14]
Android 5.1(arm v7a)
原版Xposed 89
QQ 8.4.8
和QQ相关的模块： QN QX QQCleaner 去你大爷的内置浏览器
从1.5.1降级到1.3版本成功打开设置

**Comment by CKckck626** [comment]
我也打不开

**Comment by KyuubiRan** [comment]
入口的逻辑没有改过呀 是单纯点了没反应 还是说会崩溃 还是说有个toast提示？

**Comment by Womsxd** [comment]
> 入口的逻辑没有改过呀 是单纯点了没反应 还是说会崩溃 还是说有个toast提示？

点了没反应

**Comment by CKckck626** [comment]
你好：
设备：G8441 第三方ROM 请叫我马少的包 V2.8
安卓9 
LSP1.2.2
QQ瘦身你的最新版
我安装之后我在桌面根本找不到那个软件，在LSP里点开那个模块也找不到设置的入口

Build version: v1.2.2 (5420) 
Current date: 2021-03-21 23:17:45 
Device: Sony G8441 
 
SDK: 28 
 
Stack trace:  
java.lang.IndexOutOfBoundsException: Inconsistency detected. Invalid item position 7(offset:7).state:37 rikka.widget.borderview.BorderRecyclerView{9e7225d VFED..... .......D 0,0-720,994 #7f09017b app:id/0_resource_name_obfuscated}, ***@***.***, ***@***.***, ***@***.***
	at androidx.recyclerview.widget.RecyclerView$s.k(:70)
	at androidx.recyclerview.widget.m.c(:2)
	at androidx.recyclerview.widget.m.b(:3)
	at androidx.recyclerview.widget.m.run(:6)
	at android.os.Handler.handleCallback(Handler.java:873)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loop(Looper.java:280)
	at android.app.ActivityThread.main(ActivityThread.java:6706)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)


发送自 Windows 10 版邮件应用

发件人: KyuubiRan
发送时间: 2021年3月20日 11:42
收件人: KyuubiRan/QQCleaner
抄送: CKckck626; Comment
主题: Re: [KyuubiRan/QQCleaner] 1.3.0之后的版本打不开设置 (#14)

入口的逻辑没有改过呀 是单纯点了没反应 还是说会崩溃 还是说有个toast提示？

**Comment by KyuubiRan** [comment]
> 你好： 设备：G8441 第三方ROM 请叫我马少的包 V2.8 安卓9 LSP1.2.2 QQ瘦身你的最新版 我安装之后我在桌面根本找不到那个软件，在LSP里点开那个模块也找不到设置的入口 Build version: v1.2.2 (5420) Current date: 2021-03-21 23:17:45 Device: Sony G8441 SDK: 28 Stack trace: java.lang.IndexOutOfBoundsException: Inconsistency detected. Invalid item position 7(offset:7).state:37 rikka.widget.borderview.BorderRecyclerView{9e7225d VFED..... .......D 0,0-720,994 #7f09017b app:id/0_resource_name_obfuscated}, ***@***.***, ***@***.***, ***@***.*** at androidx.recyclerview.widget.RecyclerView$s.k(:70) at androidx.recyclerview.widget.m.c(:2) at androidx.recyclerview.widget.m.b(:3) at androidx.recyclerview.widget.m.run(:6) at android.os.Handler.handleCallback(Handler.java:873) at android.os.Handler.dispatchMessage(Handler.java:99) at android.os.Looper.loop(Looper.java:280) at android.app.ActivityThread.main(ActivityThread.java:6706) at java.lang.reflect.Method.invoke(Native Method) at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493) at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858) 发送自 Windows 10 版邮件应用 发件人: KyuubiRan 发送时间: 2021年3月20日 11:42 收件人: KyuubiRan/QQCleaner 抄送: CKckck626; Comment 主题: Re: [KyuubiRan/QQCleaner] 1.3.0之后的版本打不开设置 (#14) 入口的逻辑没有改过呀 是单纯点了没反应 还是说会崩溃 还是说有个toast提示？ — You are receiving this because you commented. Reply to this email directly, view it on GitHub, or unsubscribe.

因为没有图标 所以只需要在LSP里勾选即可 请直接勾选使用
