### ISSUE TITLE
Play版QQ打不开界面

### ISSUE THREAD

**Issue by sukiko789** [KyuubiRan/QQCleaner#15]
xposed版本：Edxposed 0.5.2.2
Play版QQ版本：8.2.11
QQ瘦身版本：1.5.1

目前情况：play版qq无法打开瘦身界面，具体表现为点击无反应。play版微信7.0.17也无法运行。

**Comment by KyuubiRan** [comment]
看看[这个](https://github.com/KyuubiRan/QQCleaner/issues/13#issuecomment-801812204)

**Comment by sukiko789** [comment]
那还是只能等腾讯自己适配这个插件了
