### ISSUE TITLE
希望添加一个不会清理聊天记录图片视频的清理功能

### ISSUE THREAD

**Issue by oubeichen** [KyuubiRan/QQCleaner#21]
我用这个应用，本意是想看看能否清理未绑定聊天记录图片视频的垃圾文件（有很多这种，因为就算你把聊天记录全清空也不能清空占用空间。有可能是删除聊天记录、退群后却未清理的文件，或者已撤回的文件，或者广告、补丁缓存），结果最简单的清理就把图片全清理了。
这显然不是一般用户想要的。
不要说什么重要图片都保存。大部分用户都不会希望翻聊天记录，图片视频全灰。就算你保存了，你也很难找出这个图片的上下文，是啥时候发的，什么意思。微信虽然很容易丢消息，但是只要你不去操作，都不会清理这部分内容（几年前的图片都曾经在）。而且市面上常见清理工具都不会默认把聊天记录图片视频全清理了。至少也提供一个诸如清理7天前，30天前的操作。而不至于刚发的图片视频都看不了了（虽然可以重新下载但是体验很差而且消耗流量）
所以希望能加一个最简单的，清理用户无感知部分的选项。

**Comment by KyuubiRan** [comment]
有的呀 勾选不清理指定时间的文件即可
另外 可以选择自定义瘦身 选中你需要清理的内容 这样你可以根据自己喜好来清理（请使用最新版）
