### ISSUE TITLE
存储空间隔离与模块

### ISSUE THREAD

**Issue by bai12123** [KyuubiRan/QQCleaner#27]
大佬你好，我想问一下，用了存储空间隔离的也可以用这个模块吗？能正确识别隔离过后的目录吗？

**Comment by KyuubiRan** [comment]
应该能用 我没有试过 用的是从Context获取到的相对路径

**Comment by Agoines** [comment]
你可以先用 1.7 试试，QQ自己已经把资源扔到 Android/data 目录，应该也不需要通过储存空间进行隔离了吧，我是这样理解的
