### ISSUE TITLE
[2.0]适配虚拟按键

### ISSUE THREAD

**Issue by luckyzyx** [KyuubiRan/QQCleaner#28]
部分页面底部会被虚拟按键挡住，比如编辑配置

**Comment by KyuubiRan** [comment]
能提供一下截图吗

**Comment by luckyzyx** [comment]
> 能提供一下截图吗

![Screenshot_2022-02-28-16-41-40-15_9d26c6446fd7bb8e41d99b6262b17def.jpg](https://user-images.githubusercontent.com/46274354/155951716-209314c7-f5e6-4e90-9080-6a229d077783.jpg)

**Comment by Agoines** [comment]
已修复
![Screenshot_2022-03-07-02-17-18-603_com.tencent.mobileqq.jpg](https://user-images.githubusercontent.com/50230626/156936476-8da2b764-a076-4ed4-8463-becd20975435.jpg)
![Screenshot_2022-03-07-02-17-15-804_com.tencent.mobileqq.jpg](https://user-images.githubusercontent.com/50230626/156936478-3b78494b-9de7-4497-a7e2-8bddfbfe4925.jpg)
