### ISSUE TITLE
QQ清理和微信清理分离成单独的软件或软件改名

### ISSUE THREAD

**Issue by noctiro** [KyuubiRan/QQCleaner#32]
现在软件支持QQ微信清理，但软件还是叫做QQCleaner，会引起误解

个人建议把QQ清理和微信清理分离成不同软件
或者也可以直接改名

**Comment by KyuubiRan** [comment]
主要是懒得 太麻烦了
微信瘦身是附赠功能 我本人也不怎么用微信

**Comment by noctiro** [comment]
> 主要是懒得 太麻烦了 微信瘦身是附赠功能 我本人也不怎么用微信

但是那些只想用微信清理的人就不知道了
我是看了下更新日志才知道有这玩意
