### ISSUE TITLE
默认配置文件不应该有删除所有图片的行为

### ISSUE THREAD

**Issue by woolen-sheep** [KyuubiRan/QQCleaner#35]
希望在默认配置文件中将图片清理设置为`"enable": false`。
或者在配置界面可以预览配置项。

**Comment by KyuubiRan** [comment]
这么做会导致瘦身的效果-90%

**Comment by KyuubiRan** [comment]
qq/tim图片可以重载 删了也没啥 如果是重要的图片还请保存在本地 微信默认是false

**Comment by woolen-sheep** [comment]
> 这么做会导致瘦身的效果-90%

需要什么效果由用户自己决定比较合理，如果用户先勾选了自动清理，然后发现没有配置文件，于是启用了默认配置。这样的操作流程会导致默认配置被自动执行，可能导致重要图片被删除。

**Comment by KyuubiRan** [comment]
> > 这么做会导致瘦身的效果-90%
> 
> 需要什么效果由用户自己决定比较合理，如果用户先勾选了自动清理，然后发现没有配置文件，于是启用了配置文件。这样的操作流程会导致默认配置被自动执行，可能导致重要图片被删除。

是由用户决定的啊 但是有些人就是不会自己调 到时候又说没用 我也很无奈

**Comment by woolen-sheep** [comment]
总比默认把用户图片全删了好吧，qq图片漫游加载只能加载一段时间内的。

**Comment by woolen-sheep** [comment]
或者至少应该在显眼位置注明默认配置的行为。

**Comment by KyuubiRan** [comment]
> 总比默认把用户图片全删了好吧，qq图片漫游加载只能加载一段时间内的。

瘦身从一开始就保持默认清理图片了 不能接受的话建议换个配置文件

**Comment by woolen-sheep** [comment]
从来没有说过不能清理图片，主要问题在于

1. 用户应该能够简单的了解到在默认行为下这个插件做了什么事情
2. 默认config的入口较深，readme中没有索引，要么先加tg，要么去翻asset文件夹
3. 开这个issue目的是作为一个用户提出一点优化用户体验建议，因此提出了`或者在配置界面可以预览配置项`以及`至少应该在显眼位置注明默认配置的行为。`
4. `瘦身从一开始就保持默认清理图片了`：同样是readme缺失的问题，新的用户怎么办？
5. 按照你一直反驳我的逻辑，是不是消息记录及其索引文件也可以删除？反正可以从云端同步。是不是qq也可以删除？反正可以下载回来。

**Comment by woolen-sheep** [comment]
> 瘦身从一开始就保持默认清理图片了 不能接受的话建议换个配置文件

真正的问题在于对于新用户来说，不知道默认行为会直接导致图片被删除，这个过程是不可逆的，更换配置文件无法解决。

**Comment by Agoines** [comment]
> 从来没有说过不能清理图片，主要问题在于
> 
> 1. 用户应该能够简单的了解到在默认行为下这个插件做了什么事情
> 2. 默认config的入口较深，readme中没有索引，要么先加tg，要么去翻asset文件夹
> 3. 开这个issue目的是作为一个用户提出一点优化用户体验建议，因此提出了`或者在配置界面可以预览配置项`以及`至少应该在显眼位置注明默认配置的行为。`
> 4. `瘦身从一开始就保持默认清理图片了`：同样是readme缺失的问题，新的用户怎么办？
> 5. 按照你一直反驳我的逻辑，是不是消息记录及其索引文件也可以删除？反正可以从云端同步。是不是qq也可以删除？反正可以下载回来。

问题不在是否有默认删除图片的配置行为。而是你去使用一个东西不去看默认配置或者去官方提供的公开频道询问。

事实上，所有的选项并没有藏着掖着不告诉你有这个选项，或者偷偷做了一个什么行为。

所有信息都在应用当中，你视而不见那也没办法…

**Comment by woolen-sheep** [comment]
> 问题不在是否有默认删除图片的配置行为。而是你去使用一个东西不去看默认配置或者去官方提供的公开频道询问。
> 
> 事实上，所有的选项并没有藏着掖着不告诉你有这个选项，或者偷偷做了一个什么行为。
> 
> 所有信息都在应用当中，你视而不见那也没办法…

这不影响用户体验不好啊，不是只有bug才需要改进的。这个内容的入口深度是否过深了呢？

**Comment by Lagrio** [comment]
@woolen-sheep 你好，你需要知道的是，所谓的「默认配置」是由模块作者提供的配置。与其他配置文件一样，该配置清理项目由作者定义，并提供开关供用户自主选择。考虑到目前还没有用户撰写第三方配置的现实情况，我们在应用内加入了快速导入「默认配置」的按钮。「默认配置」同第三方配置一样，不具有特殊性。
如不在「配置」中设定默认清理项目，那么可能导致不知道如何配置清理项目的普通用户在导入配置并打开开关后得不到任何清理效果。
对于「默认配置」这一表述所造成的歧义，我们可能会在以后的更新中更改「默认配置」的名称。

**Comment by Lagrio** [comment]
@woolen-sheep 对于「配置」，在初次进行配置之后，用户进入配置页面更改清理项目的频次及可能性较低，所以将「配置」放置在二级页面而不是首页中。

**Comment by woolen-sheep** [comment]
@Lagrio 我指的不是配置这个菜单的深度

我是指 @Agoines 所提到的

> 不去看默认配置或者去官方提供的公开频道询问

**Comment by Lagrio** [comment]
@woolen-sheep 但您的表述与这句话并无明显联系。
「这不影响用户体验不好啊，不是只有bug才需要改进的。这个内容的入口深度是否过深了呢？」

**Comment by Lagrio** [comment]
@woolen-sheep 那请问您的「内容的入口」值的是什么？

**Comment by woolen-sheep** [comment]
@Lagrio 就是说， @Agoines 的意思是使用这个app之前必须先添加tg group，或者去查看配置文件内容。

但是这是一个比较长的流程，同时README没有对config的相关信息有所指引，我在上面提到过
> 默认config的入口较深，readme中没有索引，要么先加tg，要么去翻asset文件夹

这样一个流程对于一般用户不能说成一个理所当然的事情，会导致使用体验的下降，除非这个插件开发的目的仅是自用。

因此我也提到了：
> 开这个issue目的是作为一个用户提出一点优化用户体验建议，因此提出了`或者在配置界面可以预览配置项`以及`至少应该在显眼位置注明默认配置的行为`。

所以这个issue很简单，一个用户有了不好的体验，因此提了这个建议。如果开发者不愿意修改config，那么只需在README中添加对应的描述或者超链接即可。

**Comment by Lagrio** [comment]
@woolen-sheep 长按配置项可进入配置编辑页面，在该页面中您可以自行调整启用的清理项目。

**Comment by Lagrio** [comment]
> @Lagrio 就是说， @Agoines 的意思是使用这个app之前必须先添加tg group，或者去查看配置文件内容。
> 
> 但是这是一个比较长的流程，同时README没有对config的相关信息有所指引，我在上面提到过
> > 默认config的入口较深，readme中没有索引，要么先加tg，要么去翻asset文件夹
> 
> 这样一个流程对于一般用户不能说成一个理所当然的事情，会导致使用体验的下降，除非这个插件开发的目的仅是自用。
> 
> 因此我也提到了：
> > 开这个issue目的是作为一个用户提出一点优化用户体验建议，因此提出了`或者在配置界面可以预览配置项`以及`至少应该在显眼位置注明默认配置的行为`。
> 
> 所以这个issue很简单，一个用户有了不好的体验，因此提了这个建议。如果开发者不愿意修改config，那么只需在README中添加对应的描述或者超链接即可。

`所谓的「默认配置」是由模块作者提供的配置。与其他配置文件一样，该配置清理项目由作者定义，并提供开关供用户自主选择。`

**Comment by woolen-sheep** [comment]
不是，我感觉我们一直说的不是一件事情啊。

> 所谓的「默认配置」是由模块作者提供的配置。与其他配置文件一样，该配置清理项目由作者定义，并提供开关供用户自主选择。

你不应该对我说这个，我没有攻击作者的意思，你这样对我解释也没有过多的作用。应该把这句声明写进README，这样能帮助到之后关注这个项目的用户。

如果不想写我一会开个pr。

@Lagrio

**Comment by Lagrio** [comment]
@woolen-sheep 那您的诉求是现有的「默认配置」不应该默认启用图片清理吗？

**Comment by woolen-sheep** [comment]
> @woolen-sheep 那您的诉求是现有的「默认配置」不应该默认启用图片清理吗？

我仍然这么认为，修改README只是一个替代方案。

最好是默认关闭同时完善README，告知用户如何达到最好的清理效果。但是你们一直不同意这个想法。

**Comment by Lagrio** [comment]
> > @woolen-sheep 那您的诉求是现有的「默认配置」不应该默认启用图片清理吗？
> 
> 我仍然这么认为，修改README只是一个替代方案。
> 
> 最好是默认关闭同时完善README，告知用户如何达到最好的清理效果。但是你们一直不同意这个想法。

`所谓的「默认配置」是由模块作者提供的配置。与其他配置文件一样，该配置清理项目由作者定义，并提供开关供用户自主选择。考虑到目前还没有用户撰写第三方配置的现实情况，我们在应用内加入了快速导入「默认配置」的按钮。「默认配置」同第三方配置一样，不具有特殊性。
如不在「配置」中设定默认清理项目，那么可能导致不知道如何配置清理项目的普通用户在导入配置并打开开关后得不到任何清理效果。
对于「默认配置」这一表述所造成的歧义，我们可能会在以后的更新中更改「默认配置」的名称。`

目前的「默认配置」名称中的「默认」确实有歧义。如前所述，目前的「默认配置」是由 KyuubiRan 所撰写，其提供的默认清理项目为 KyuubiRan 所认为的应为用户默认开启的项目。

对于「取消默认启用图片清理」这一需求，我们认为您的预设立场很可能为「用户认为 QQ 中的聊天图片很重要」。**但我们始终认为重要图片应保存至本地或添加至 QQ 收藏中**，且与微信不同的是， QQ 具有消息云同步功能。

我们已在软件内为**需要**调整清理项目的用户提供了可视化开关，用户可自行启用或停用目前「默认配置」中所提供的清理项目。

对于「在显眼处注明默认配置的行为」这一需求，目前「默认配置」清理项目数量较多，在`主界面`或`编辑配置`页面注明某一配置的清理项目不现实。

目前大多数普通用户并不会通过 Github 渠道下载该模块，更改 `Readme.md` 文件并不能对大多数普通用户起到提示与警告作用。当然，我们欢迎您提交 Pull Request 以完善 `Readme.md` 文件。

我们可能会在之后的版本中更改「默认配置」的名称，调整从`编辑配置`页面进入`配置页面`的 UI 逻辑，并撰写免责声明。

**Comment by xslingcn** [comment]
可否为添加一个醒目的弹出式提示，警告用户该操作会删除所有聊天图片？这类高危操作按理应当在首次进行前要求用户进行二次确认。点了清理后聊天图片全部被清除掉实在是太痛苦了。

**Comment by Vogadero** [comment]
上面几个脑残还改配置，直接用清理软件不行嘛？又贪又作，恶不恶心
