### ISSUE TITLE
QWallet启动失败！

### ISSUE THREAD

**Issue by Cowboy-Shuai** [KyuubiRan/QQCleaner#4]
QQ瘦身1.2.4 模块
**不知道是不是因为QQ版本不是最新版，导致提示“QWallet启动失败！” 无法发红包和领取红包**
太极·阴 6.4.0
QQ 7.7.6(899) (GooglePlay版)
荣耀9 安卓版本 9 EMUI版本 9.1.0

**Comment by KyuubiRan** [comment]
这好像不关我瘦身模块的事（
