### ISSUE TITLE
QQcleaner和QQcleaner lite的在功能上有区别吗

### ISSUE THREAD

**Issue by 369wym** [KyuubiRan/QQCleaner#40]
如题

**Comment by Agoines** [comment]
功能上没有，原版在部分机型可能白屏，但是 UI 相对好看，lite 版会更轻一些，也没有白屏这个问题。

**Comment by 369wym** [comment]
> 但是上没有，原版在功能部分可能出现问题的白屏，UI美观，精简版会更轻一些，也没有这个白屏。

谢谢
