### ISSUE TITLE
关于QQ收藏卡死问题

### ISSUE THREAD

**Issue by MJRweb** [KyuubiRan/QQCleaner#5]
不知是本模块原因还是和其他冲突原因，我edxp把本模块下了QQ收藏不会卡死没问题，一安上进QQ收藏就卡死

**Comment by MJRweb** [comment]
望开发者排查一下

**Comment by KyuubiRan** [comment]
按理来说我的模块不会导致别的地方出问题 我总共就hook了qq一个地方 关于界面 我在那里创建了一个item 别的地方都没动过了。。你看看是不是别的模块导致的

**Comment by MJRweb** [comment]
我重启了QQ几次貌似可以了，解决了
