### ISSUE TITLE
点不开设置

### ISSUE THREAD

**Issue by AceMONKEY519** [KyuubiRan/QQCleaner#8]
![Screenshot_20210303-112304](https://user-images.githubusercontent.com/19290973/109748219-72f7d700-7c13-11eb-8df8-dd1b0dba9e24.jpg)
何解

**Comment by AceMONKEY519** [comment]
等了好久也不行

**Comment by KyuubiRan** [comment]
请尝试重启QQ 原因是资源hook失败了 就算打开也会导致QQ崩溃

**Comment by Whuihuan** [comment]
> 请尝试重启QQ 原因是资源hook失败了 就算打开也会导致QQ崩溃

重启也是不行

**Comment by KyuubiRan** [comment]
> > 请尝试重启QQ 原因是资源hook失败了 就算打开也会导致QQ崩溃
> 
> 重启也是不行

试试旧版本正常吗
